rules:
  validate-status:
    description: Comprueba que x-app-type tiene un valor valido
    given: $.['x-app-type']
    then:
      function: pattern
      functionOptions:
        match: ^(?:internal|client|both)$
    severity: error
    
